name: Create Archive

on:
  push:
    branches:
      - release

env:
  PROJECT: Nextcloud.xcodeproj
  SCHEME: Nextcloud
  SERVER_BRANCH: stable30
  PHP_VERSION: 8.3

jobs:
  build:
    name: Build
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v5

    - name: Download GoogleService-Info.plist
      run: wget "https://raw.githubusercontent.com/firebase/quickstart-ios/master/mock-GoogleService-Info.plist" -O GoogleService-Info.plist

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: '26.2'

    - name: Run Xcode Build
      run: |
        set -o pipefail && \
        xcodebuild archive \
        -scheme "${{ env.SCHEME }}" \
        -configuration Release \
        -sdk iphoneos \
        -archivePath build/Nextcloud.xcarchive \
        CODE_SIGNING_ALLOWED=NO \
        | xcbeautify --quieter

    - name: Upload Build Products
      uses: actions/upload-artifact@v4
      with:
        name: Nextcloud for iOS
        path: build/Nextcloud.xcarchive
        retention-days: 4
